### ISSUE TITLE
Add additional platform integration testing to CI 

### ISSUE THREAD

**Issue by mikebrow** [containerd/imgcrypt#38]
Given differences in build and dependencies between the various platforms we should add additional platform build and integration testing to CI/CD.

- [ ] windows
- [ ] ____

**Comment by stefanberger** [comment]
@estesp @mikebrow  I guess I need your attention for this kind of issue. So the failing build environment is mingw, right?

We have prevented our builds from failing when a cross compiler is used. For this we have two files in ocicrypt:
- +build cgo: https://github.com/containers/ocicrypt/blob/master/crypto/pkcs11/pkcs11helpers.go
- _build !cgo: https://github.com/containers/ocicrypt/blob/master/crypto/pkcs11/pkcs11helpers_nocgo.go

My guess is that the mingw environment fails because it tries to compile the former rather than the latter. Can we somehow extend this build line with an identifier for mingw?

**Comment by mikebrow** [comment]
closing for now till we get further instruction from the windows team...
